const Products = [
    {
        id: '01',
        category: 'newArrival',
        thumbnail: 'assets/product_image/Remote_Car.png',
        Product_Name: "Remote Car",
        color: ['red'],
        rating: {
            stars: 4.5, 
            count: 1409,
        },
        current_price: 699,
        original_price: 1999,
        discount_percentage: 34,
        return_period: 7,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'Remote Control Toys',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
    {
        id: '02',
        category: 'newArrival',
        thumbnail: 'assets/product_image/Britt_Teddy_Bear.png',
        Product_Name: "Britt Teddy Bear ",
        color: ['red', 'yellow'],
        rating: {
            stars: 4.5, 
            count: 3094,
        },
        current_price: 296,
        original_price: 1554,
        discount_percentage: 80,
        return_period: 10,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'Britt Teddy Bear Toys',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },


    },
    {
        id: '03',
        category: 'newArrival',
        thumbnail: 'assets/product_image/Educational_Toys.png',
        Product_Name: "Educational Toys",
        color: ['yellow'],
        rating: {
            stars: 4.5, 
            count: 5099,
        },
        current_price: 199,
        original_price: 800,
        discount_percentage: 24,
        return_period: 14,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Educational Toys',
        Tag: 'Educational Toys',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
    {
        id: '04',
        category: 'newArrival',
        thumbnail: 'assets/product_image/Musical_Instruments.png',
        Product_Name: "Musical instruments",
        color: ['red'],
        rating: {
            stars: 4.3, 
            count: 189,
        },
        current_price: 675,
        original_price: 1932,
        discount_percentage: 34,
        return_period: 7,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'Musical instruments Toys',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
    {
        id: '05',
        category: 'newArrival',
        thumbnail: 'assets/product_image/Plush_Toys.png',
        Product_Name: "Plush Toys",
        color: ['pink'],
        rating: {
            stars: 4.4, 
            count: 859,
        },
        current_price: 454,
        original_price: 899,
        discount_percentage: 94,
        return_period: 14,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'Plush Toys',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
    {
        id: '06',
        category: 'newArrival',
        thumbnail: 'assets/product_image/Action_Figures_Dolls.png',
        Product_Name: "Action Figures & Dolls",
        color: ['Yellow', 'red'],
        rating: {
            stars: 4.5, 
            count: 1009,
        },
        current_price: 649,
        original_price: 999,
        discount_percentage: 64,
        return_period: 14,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'Action Figures & Dolls Toys',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
    {
        id: '07',
        category: 'newArrival',
        thumbnail: 'assets/product_image/Remote_Control_Vehicles.png',
        Product_Name: "Remote Control Vehicles",
        color: ['blue'],
        rating: {
            stars: 4.2, 
            count: 209,
        },
        current_price: 875,
        original_price: 1499,
        discount_percentage: 25,
        return_period: 10,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'Remote Control Vehicles Toys',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
    {
        id: '08',
        category: 'newArrival',
        thumbnail: 'assets/product_image/Sports_Activity_Toys.png',
        Product_Name: "Sports & Activity Toys",
        color: ['green'],
        rating: {
            stars: 4.3, 
            count: 1009,
        },
        current_price: 255,
        original_price: 799,
        discount_percentage: 32,
        return_period: 14,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'Sports & Activity Toys',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },

    // Trending Now
    {
        id: '09',
        category: 'trending',
        thumbnail: 'assets/product_image/Electric_Ride-Ons.png',
        Product_Name: "Electric Ride-Ons",
        color: ['red'],
        rating: {
            stars: 4.4, 
            count: 1879,
        },
        current_price: 1420,
        original_price: 2549,
        discount_percentage: 55,
        return_period: 14,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'Electric Ride-Ons',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
    {
        id: '10',
        category: 'trending',
        thumbnail: 'assets/product_image/Balance_Bikes.png',
        Product_Name: "Balance Bikes",
        color: ['pink'],
        rating: {
            stars: 4.4, 
            count: 879,
        },
        current_price: 1699,
        original_price: 2449,
        discount_percentage: 67,
        return_period: 10,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'Balance Bikes',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
    {
        id: '11',
        category: 'trending',
        thumbnail: 'assets/product_image/Scooters.png',
        Product_Name: "Scooters",
        color: ['red'],
        rating: {
            stars: 4.5, 
            count: 799,
        },
        current_price: 1000,
        original_price: 1200,
        discount_percentage: 10,
        return_period: 7,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'Scooters',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
    {
        id: '12',
        category: 'trending',
        thumbnail: 'assets/product_image/Tricycles.png',
        Product_Name: "Tricycles",
        color: ['aqua'],
        rating: {
            stars: 4.5, 
            count: 799,
        },
        current_price: 1999,
        original_price: 4999,
        discount_percentage: 39,
        return_period: 14,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'Tricycles',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
    {
        id: '13',
        category: 'trending',
        thumbnail: 'assets/product_image/Kids_Bicycles.png',
        Product_Name: "Kids Bicycles",
        color: ['black'],
        rating: {
            stars: 4.5, 
            count: 1099,
        },
        current_price: 11998,
        original_price: 21999,
        discount_percentage: 54,
        return_period: 14,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'Kids Bicycles',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
    {
        id: '14',
        category: 'trending',
        thumbnail: 'assets/product_image/Push_Ride-Ons.png',
        Product_Name: "Push Ride-Ons",
        color: ['white'],
        rating: {
            stars: 4.5, 
            count: 1587,
        },
        current_price: 899,
        original_price: 3999,
        discount_percentage: 80,
        return_period: 17,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'Push Ride-Ons',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
    {
        id: '15',
        category: 'trending',
        thumbnail: 'assets/product_image/Go_Karts.png',
        Product_Name: "Go Karts",
        color: ['red'],
        rating: {
            stars: 4.5, 
            count: 1587,
        },
        current_price: 459,
        original_price: 1199,
        discount_percentage: 76,
        return_period: 17,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'Go Karts',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
    {
        id: '16',
        category: 'trending',
        thumbnail: 'assets/product_image/Hoverboards.png',
        Product_Name: "Hoverboards",
        color: ['black'],
        rating: {
            stars: 4.5, 
            count: 1587,
        },
        current_price: 1299,
        original_price: 4599,
        discount_percentage: 70,
        return_period: 17,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'Go Karts',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
    {
        id: '17',
        category: 'toprated',
        thumbnail: 'assets/product_image/B_Agile_Stroller.png',
        Product_Name: "B-Agile Stroller",
        color: ['red'],
        rating: {
            stars: 4.5, 
            count: 1587,
        },
        current_price: 27299,
        original_price: 37786,
        discount_percentage: 28,
        return_period: 14,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'B-Agile Stroller',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
    {
        id: '18',
        category: 'toprated',
        thumbnail: 'assets/product_image/CADDLE_TOES_High_Speed.png',
        Product_Name: "CADDLE & TOES High Speed",
        color: ['green'],
        rating: {
            stars: 4.5, 
            count: 1207,
        },
        current_price: 1199,
        original_price: 1999,
        discount_percentage: 40,
        return_period: 14,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'CADDLE & TOES High Speed',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
    {
        id: '19',
        category: 'toprated',
        thumbnail: 'assets/product_image/Univocean_Geometric_Sorting.png',
        Product_Name: "Univocean Geometric Sorting Board Stack Set",
        color: ['Yellow'],
        rating: {
            stars: 4.6, 
            count: 1507,
        },
        current_price: 1344,
        original_price: 2499,
        discount_percentage: 46,
        return_period: 14,
        delivery_date: '10 Oct 2025',
        SKU:'29045-SD-7',
        Categories:'Electric Toys',
        Tag: 'Univocean Geometric Sorting',
        Description: {
            dec_text : 'Experience the thrill of high-speed stunts and mesmerizing music with our Musical Stunt Car! This innovative toy car is designed to perform gravity-defying flips and spins, making every playtime an exhilarating adventure. With its 360° rotation capability, flashing lights, and catchy music, this stunt car promises hours of non-stop entertainment for kids of all ages.',
            Key_Features : [
                'Performs 360° flips and spins for jaw-dropping stunts.',
                'Features vibrant multicolor flashing lights for added visual excitement.',
                'Plays catchy music tunes to enhance the play experience.',
                'Durable construction ensures long-lasting playtime fun.',
                'Easy-to-use remote control allows for precise maneuvering.',
            ],
            Specifications: {
                Material : 'High-quality plastic',
                Dimensions : '6 inches (length) x 4 inches (width) x 3 inches (height)',
                Recommended_Age : 'Suitable for children aged 3 years and above',
                Battery_Requirements : 'Requires 3 AA batteries (not included)',
            },
            Benefits : [
                'Encourages imaginative play and creativity.',
                'Enhances hand-eye coordination and fine motor skills.',
                'Promotes active play and physical activity.',
                'Provides sensory stimulation through lights and music.',
            ],
        },
    },
]
